### ISSUE TITLE
I see a warning in Version 1.0.3

### ISSUE THREAD

**Issue by RinDevJunior** [AmineVolk/react-terminal-view#1]
![image](https://user-images.githubusercontent.com/22781131/93745758-3ebccb00-fc1e-11ea-9631-1e45ddc4dcaa.png)
Hi there, I have pull your package and it works perfectly.
But I see this warning in console log, (Just want to notify you about that. No need any fix for me)

![image](https://user-images.githubusercontent.com/22781131/93745942-8e02fb80-fc1e-11ea-9455-937e0acf996e.png)
And this is my implement

**Comment by AmineVolk** [comment]
Thanks a lot for your time @RinDevJunior ^^,
it's a typo error and now it's solved (v1.0.4)

**Comment by RinDevJunior** [comment]
You're welcome
So I will close this issue here
